services:
  frontend:
    build:
      context: ./frontend
    image: tylerpac-frontend:latest
    container_name: tylerpacdevwebsite-frontend
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tylerpac.rule=Host(\"tylerpac.dev\",\"www.tylerpac.dev\")"
      - "traefik.http.routers.tylerpac.entrypoints=websecure"
      - "traefik.http.routers.tylerpac.tls=true"
      - "traefik.http.routers.tylerpac.tls.certresolver=myresolver"
      - "traefik.http.services.tylerpac.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
