pipeline {
  agent any

  tools {
    maven 'Maven 3.8.5'
  }

  environment {
    IMAGE_NAME = "tylerpacdevelopment/mainsite"
    CONTAINER_NAME = "mainsite"
  }

  stages {
    stage('Clean & Build JAR') {
      steps {
        dir('mainsite') {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('mainsite') {
          sh "docker build -t ${IMAGE_NAME}:latest ."
        }
      }
    }

    stage('Deploy Container') {
      steps {
        script {
          // Stop and remove existing container
          sh "docker stop ${CONTAINER_NAME} || true"
          sh "docker rm ${CONTAINER_NAME} || true"

          // Run new container
          sh """
            docker run -d \
              --name ${CONTAINER_NAME} \
              -p 8080:8080 \
              --network=backend \
              ${IMAGE_NAME}:latest
          """
        }
      }
    }
  }

  post {
    success {
      echo "✅ mainsite deployed."
      httpRequest httpMode: 'POST',
        contentType: 'APPLICATION_JSON',
        requestBody: """{
            "job": "${env.JOB_NAME}",
            "branch": "${env.BRANCH_NAME}",
            "build": "${env.BUILD_NUMBER}",
            "status": "SUCCESS",
            "url": "${env.BUILD_URL}"
        }""",
        url: 'https://n8n.tylerpac.dev/webhook/TylerPacDevelopment'
    }

    failure {
      echo "❌ mainsite Failed to deploy."
      httpRequest httpMode: 'POST',
        contentType: 'APPLICATION_JSON',
        requestBody: """{
            "job": "${env.JOB_NAME}",
            "branch": "${env.BRANCH_NAME}",
            "build": "${env.BUILD_NUMBER}",
            "status": "FAILURE",
            "url": "${env.BUILD_URL}"
        }""",
        url: 'https://n8n.tylerpac.dev/webhook/TylerPacDevelopment'
    }
  }
}
