pipeline {
  agent any

  tools {
    maven 'Maven 3.8.5'
  }

  environment {
    IMAGE_NAME = "TylerPacDevelopment/mainsite"
  }

  stages {
    stage('Build WAR') {
      steps {
        dir('mainsite') {
          sh 'mvn clean package'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('mainsite') {
          sh "docker build -t ${IMAGE_NAME}:latest ."
        }
      }
    }

    stage('Deploy Container') {
      steps {
        sh "docker stop ${IMAGE_NAME} || true"
        sh "docker rm ${IMAGE_NAME} || true"
        sh "docker run -d --name ${IMAGE_NAME} -p 8080:8080 --network=backend ${IMAGE_NAME}:latest"
      }
    }
  }

  post {
    success {
          echo "✅ mainsite deployed."
          httpRequest httpMode: 'POST',
                      contentType: 'APPLICATION_JSON',
                      requestBody: """{
                          "job": "${env.JOB_NAME}",
                          "branch": "${env.BRANCH_NAME}",
                          "build": "${env.BUILD_NUMBER}",
                          "status": "SUCCESS",
                          "url": "${env.BUILD_URL}"
                      }""",
                      url: 'https://n8n.tylerpac.dev/webhook/TylerPacDevelopment'
      }
      failure {
          echo "❌ mainsite Failed to deploy."
          httpRequest httpMode: 'POST',
                      contentType: 'APPLICATION_JSON',
                      requestBody: """{
                          "job": "${env.JOB_NAME}",
                          "branch": "${env.BRANCH_NAME}",
                          "build": "${env.BUILD_NUMBER}",
                          "status": "FAILURE",
                          "url": "${env.BUILD_URL}"
                      }""",
                      url: 'https://n8n.tylerpac.dev/webhook/TylerPacDevelopment'
      }
  }
}
